image: ryp123/android-sdk:ubuntu


# before_script and cache section based heavily on
# https://stackoverflow.com/a/45855551/5960886
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/
    - app/build/

stages:
  - build
  - code-analysis
  - test

build:
    stage: build
    script: ./gradlew assemble

code-analysis:
  stage: code-analysis
  script:
    - ./gradlew lint
    - ./gradlew checkstyle
    - ./gradlew findbugs
  artifacts:
    when: always
    paths:
      - app/build/reports/lint-results.html
      - build/reports/checkstyle/checkstyle.html
      - build/reports/findbugs/findbugs.html
    expire_in: 1 week

  test:
    stage: test
    script:
      - ./gradlew test
       
