image: ryp123/android-sdk:ubuntu

stages:
  - lint

linter:
  stage: lint
  script:
    - ./gradlew lint
    - ./gradlew checkstyle
  artifacts:
    when: always
    paths:
      - app/build/reports/lint-results.html
      - build/reports/checkstyle/checkstyle.html
    expire_in: 1 week
